name: publish_cicd

on:
 workflow_dispatch:
 push:
    branches:
    - main
 
env:
  AZURE_WEBAPP_NAME: cid-cd-example
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  

jobs:
  publsih:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
         dotnet-version: '3.1.x'
         
      - name: Restore
        run: dotnet restore ./CI-CID-DEMO.sln
           
      - name: Build
        run: dotnet build ./CI-CID-DEMO.sln --configuration Release
             
      - name: Publish
        run: dotnet publish ./CI-CID-DEMO.sln --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
           appname: ${{ env.AZURE_WEBAPP_NAME }}
           publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
           package:  "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
